AllCops:
  RubyInterpreters:
    - ruby
    - macruby
    - rake
    - jruby
    - rbx
  # Include common Ruby source files.
  Include:
    - '**/*.rb'
    - '**/*.arb'
    - '**/*.axlsx'
    - '**/*.builder'
    - '**/*.fcgi'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.god'
    - '**/*.jb'
    - '**/*.jbuilder'
    - '**/*.mspec'
    - '**/*.opal'
    - '**/*.pluginspec'
    - '**/*.podspec'
    - '**/*.rabl'
    - '**/*.rake'
    - '**/*.rbuild'
    - '**/*.rbw'
    - '**/*.rbx'
    - '**/*.ru'
    - '**/*.ruby'
    - '**/*.spec'
    - '**/*.thor'
    - '**/*.watchr'
    - '**/.irbrc'
    - '**/.pryrc'
    - '**/.simplecov'
    - '**/buildfile'
    - '**/Appraisals'
    - '**/Berksfile'
    - '**/Brewfile'
    - '**/Buildfile'
    - '**/Capfile'
    - '**/Cheffile'
    - '**/Dangerfile'
    - '**/Deliverfile'
    - '**/Fastfile'
    - '**/*Fastfile'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Jarfile'
    - '**/Mavenfile'
    - '**/Podfile'
    - '**/Puppetfile'
    - '**/Rakefile'
    - '**/rakefile'
    - '**/Snapfile'
    - '**/Steepfile'
    - '**/Thorfile'
    - '**/Vagabondfile'
    - '**/Vagrantfile'
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'test/test_helper.rb'
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/application_system_test_case.rb'
    - 'config/puma.rb'
    - 'config/initializers/*'
    - 'config/boot.rb'
    - 'config/application.rb'
    - 'config.ru'
    - 'bin/*'
    - 'app/models/application_record.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/jobs/application_job.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/channels/application_cable/channel.rb'
    - 'app/channels/application_cable/connection.rb'
    - 'config/environments/development.rb'
    - 'Rakefile'
    - 'Gemfile'
    - 'db/*'
    - 'db/*/*'
  NewCops: enable
  SuggestExtensions: false
Style/FrozenStringLiteralComment:
  Enabled: false
StringLiterals:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false